// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8qFoIC-d-8r50kIelCKuy0dDYkSirtJ4',
    appId: '1:185934436559:web:3db31e32aa19e34e79bfba',
    messagingSenderId: '185934436559',
    projectId: 'hal-app-bdd31',
    authDomain: 'hal-app-bdd31.firebaseapp.com',
    storageBucket: 'hal-app-bdd31.appspot.com',
    measurementId: 'G-DNP54SQXYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLfKnwM1x5I1fZoJZa8XTCz-yDiq8bEv4',
    appId: '1:185934436559:android:45a747e315bcb36c79bfba',
    messagingSenderId: '185934436559',
    projectId: 'hal-app-bdd31',
    storageBucket: 'hal-app-bdd31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYMPiMl5rmF5ZvpB05JxNbdbQzGsZ6VcU',
    appId: '1:185934436559:ios:5d38583a2ac754af79bfba',
    messagingSenderId: '185934436559',
    projectId: 'hal-app-bdd31',
    storageBucket: 'hal-app-bdd31.appspot.com',
    iosBundleId: 'com.ojasspace.hal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8qFoIC-d-8r50kIelCKuy0dDYkSirtJ4',
    appId: '1:185934436559:web:93eedeb85c4fc64479bfba',
    messagingSenderId: '185934436559',
    projectId: 'hal-app-bdd31',
    authDomain: 'hal-app-bdd31.firebaseapp.com',
    storageBucket: 'hal-app-bdd31.appspot.com',
    measurementId: 'G-0T1YBQW16H',
  );
}
